# OutputFolder: "wallpapers/new"
EnableImagePreviewing: true
InlineImagePreview: true

themes:
  - name: "oxocarbon-dark"
    colors:
        - "#161616"
        - "#262626"
        - "#393939"
        - "#525252"
        - "#dde1e6"
        - "#f2f4f8"
        - "#ffffff"
        - "#08bdba"
        - "#ee5396"
        - "#ff7eb6"
        - "#ff6f00"
        - "#42be65"
        - "#3ddbd9"
        - "#33b1ff"
        - "#be95ff"
        - "#82cfff"
  - name: "muted"
    colors:
       - "#121212"
       - "#1c1b1b"
       - "#2e2d2d"
       - "#4a4848"
       - "#636161"
       - "#898585"
       - "#b7b2b2"
       - "#ffffff"
       - "#c48786"
       - "#bd8b51"
       - "#e8ebb0"
       - "#9dd1a4"
       - "#7dc7b8"
       - "#86aac4"
       - "#e4c3fa"
       - "#8c705b"
      
